# Generated by Django 3.2.7 on 2021-09-19 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cellphone',
            field=models.CharField(default='0', max_length=14),
        ),
        migrations.AlterField(
            model_name='student',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='rg',
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
