# Generated by Django 3.2.7 on 2021-09-19 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20210919_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cellphone',
            field=models.CharField(max_length=14),
        ),
    ]
