# Generated by Django 3.2.7 on 2021-09-19 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_student_cellphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cellphone',
            field=models.CharField(max_length=15),
        ),
    ]
