EASY_LEVEL = 1
MEDIUM_LEVEL = 2
HARD_LEVEL = 3

LEVELS_VALUES = (
    (EASY_LEVEL, 'Fácil'),
    (MEDIUM_LEVEL, 'Médio'),
    (HARD_LEVEL, 'Difícil')
)

MORNING_TIME_COURSE = 1
AFTERNOON_TIME_COURSE = 2
NIGHT_TIME_COURSE = 3

TIME_COURSE_VALUES = (
    (MORNING_TIME_COURSE, 'Matutino'),
    (AFTERNOON_TIME_COURSE, 'Vespertino'),
    (NIGHT_TIME_COURSE, 'Noturno')
)